---
engines:
  csslint:
    enabled: false
  eslint:
    enabled: true
  fixme:
    enabled: true
  phpcodesniffer:
    enabled: true
  phpmd:
    enabled: true
  radon:
    enabled: true
  duplication:
    enabled: false
    config:
      languages:
      - php
      - javascript
ratings:
  paths:
  - "**.css"
  - "**.js"
  - "**.php"
exclude_paths:
- node_modules/**/*
- vendor/**/*
