---
engines:
  eslint:
    enabled: true
  fixme:
    enabled: true
  phpcodesniffer:
    enabled: true
  phpmd:
    enabled: true
  radon:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.php"
exclude_paths:
- node_modules/**/*
- vendor/**/*
